if(EXISTS "/home/misan/packing2D/packing_tests[1]_tests.cmake")
  include("/home/misan/packing2D/packing_tests[1]_tests.cmake")
else()
  add_test(packing_tests_NOT_BUILT packing_tests_NOT_BUILT)
endif()
