add_test([=[MAreaTest.ConstructionAndProperties]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=MAreaTest.ConstructionAndProperties]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MAreaTest.ConstructionAndProperties]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MAreaTest.PieceWithHole]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=MAreaTest.PieceWithHole]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MAreaTest.PieceWithHole]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MAreaTest.Transformations]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=MAreaTest.Transformations]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MAreaTest.Transformations]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MAreaTest.Intersection]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=MAreaTest.Intersection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MAreaTest.Intersection]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BinTest.Construction]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=BinTest.Construction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BinTest.Construction]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BinTest.BoundingBoxPacking_SinglePiece]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=BinTest.BoundingBoxPacking_SinglePiece]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BinTest.BoundingBoxPacking_SinglePiece]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BinTest.BoundingBoxPacking_PieceTooLarge]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=BinTest.BoundingBoxPacking_PieceTooLarge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BinTest.BoundingBoxPacking_PieceTooLarge]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BinTest.BoundingBoxPacking_MultiplePieces]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=BinTest.BoundingBoxPacking_MultiplePieces]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BinTest.BoundingBoxPacking_MultiplePieces]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BinTest.Compress]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=BinTest.Compress]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BinTest.Compress]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BinTest.DropPieces_Stacking]=]  /home/misan/packing2D/packing_tests [==[--gtest_filter=BinTest.DropPieces_Stacking]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BinTest.DropPieces_Stacking]=]  PROPERTIES WORKING_DIRECTORY /home/misan/packing2D SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  packing_tests_TESTS MAreaTest.ConstructionAndProperties MAreaTest.PieceWithHole MAreaTest.Transformations MAreaTest.Intersection BinTest.Construction BinTest.BoundingBoxPacking_SinglePiece BinTest.BoundingBoxPacking_PieceTooLarge BinTest.BoundingBoxPacking_MultiplePieces BinTest.Compress BinTest.DropPieces_Stacking)
